### ISSUE TITLE
关机模式

### ISSUE THREAD

**Issue by bulesky89857** [ypq123456789/TrafficCop#2]
关机模式,如果监测时间间隔1分钟,可能会导致操作时间短而导致开机后再次关机

**Comment by ypq123456789** [comment]
关机模式本来就是流量超限后觉得没必要操作机子，为了图省事而选择关机的呀，如果关机后还要再次开机，不建议选择关机模式

**Comment by ypq123456789** [comment]
另外，不知道是不是bug，我的阿里云ecs实测，关机模式手动开机后不会再次因为超限而关机了，很神奇。。。

**Comment by bulesky89857** [comment]
> 另外，不知道是不是bug，我的阿里云ecs实测，关机模式手动开机后不会再次因为超限而关机了，很神奇。。。

好吧
