### ISSUE TITLE
自定义安装目录

### ISSUE THREAD

**Issue by NPCDW** [ypq123456789/TrafficCop#3]
`acme.sh` 这种 `shell` 程序是安装在用户目录下的一个隐藏目录中，`TrafficCop` 能否也安装到 `/root/.trafficCop` 目录下，或者给用户可以自定义安装目录的选项

主要是我看到脚本里的目录是写死在 `/root/*` 目录下，如果我的根目录下存放了一些临时文件，那我就不知道哪些应该删除哪些不应该删除了

![image](https://github.com/ypq123456789/TrafficCop/assets/32638459/7cd523a2-de9a-4b52-be29-1f35b272dce2)

![image](https://github.com/ypq123456789/TrafficCop/assets/32638459/eae55f79-3cbf-4dad-bae8-2be6a2115d9c)

**Comment by ypq123456789** [comment]
已更新：切换工作目录，迁移原配置文件。不过，可能会带来无限生成monitor进程的新bug，目前偶发，不是每次都触发，如果你也发现了可以说一声。

**Comment by NPCDW** [comment]
移除流量限制的这个脚本的工作目录好像没改，是否需要改动一下

https://github.com/ypq123456789/TrafficCop/blob/main/remove_traffic_limit.sh

**Comment by ypq123456789** [comment]
> 移除流量限制的这个脚本的工作目录好像没改，是否需要改动一下
> 
> https://github.com/ypq123456789/TrafficCop/blob/main/remove_traffic_limit.sh

差点忘了，谢谢提醒。改过来了
